from tutorials.views.calendar import *
from tutorials.views.dashboard import *
from tutorials.views.entity import *
from tutorials.views.home import *
from tutorials.views.invoice import *
from tutorials.views.lesson import *
from tutorials.views.mixin import *
from tutorials.views.profile import *
from tutorials.views.request import *
from tutorials.views.subject import *
from tutorials.views.tutor_availability import *
from tutorials.views.update_request import *
from tutorials.views.user_authentication import *