# Generated by Django 5.1.2 on 2024-12-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
