# Generated by Django 5.1.2 on 2024-12-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
