# Generated by Django 5.1.2 on 2024-11-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c++', 'C++'), ('java', 'Java')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_frequency',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly')]),
        ),
    ]
