
# Generated by Django 5.1.2 on 2024-11-30 13:02
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c++', 'C++'), ('java', 'Java')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_frequency',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly')]),
        ),

        migrations.CreateModel(
            name='TutorBio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=255)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'subject_id')},
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(through='tutorials.TutorSubjects', to='tutorials.subject'),
        ),
    ]
