# Generated by Django 5.1.2 on 2024-12-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='day',
        ),
    ]
