# Generated by Django 5.1.2 on 2024-12-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_lessonrequest_day_alter_tutoravailability_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('tutor', 'student', 'subject_id')},
        ),
    ]
