# Generated by Django 5.1.2 on 2024-11-15 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_admin_lesson_student_subject_term_tutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[(3, 'Java'), (1, 'Python'), (2, 'C++')], max_length=10)),
                ('lesson_time', models.TimeField()),
                ('lesson_day', models.CharField(choices=[(3, 'Wednesday'), (5, 'Friday'), (6, 'Saturday'), (1, 'Monday'), (2, 'Tuesday'), (7, 'Sunday'), (4, 'Thursday')], max_length=9)),
                ('lesson_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
