# Generated by Django 5.1.2 on 2024-12-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_rename_lesson_day_lessonrequest_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonrequest',
            old_name='request',
            new_name='request_id',
        ),
    ]
