# Generated by Django 5.1.2 on 2024-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_student_has_new_lesson_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=3),
        ),
    ]
