# Generated by Django 5.1.2 on 2024-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_lessonrequest_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.CharField(choices=[('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('O', 'Once')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='frequency',
            field=models.CharField(choices=[('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('O', 'Once')], max_length=10),
        ),
    ]
