# Generated by Django 5.1.2 on 2024-12-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_user_about_me_delete_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_new_lesson_notification',
            field=models.BooleanField(default=False),
        ),
    ]
