# Generated by Django 5.1.2 on 2024-12-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_rename_request_lessonrequest_request_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonrequest',
            unique_together={('request_id',)},
        ),
    ]
