# Generated by Django 5.1.2 on 2024-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_lessonrequest_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_day',
            field=models.CharField(choices=[(3, 'Wednesday'), (1, 'Monday'), (2, 'Tuesday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (4, 'Thursday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='subject',
            field=models.CharField(choices=[(3, 'Java'), (2, 'C++'), (1, 'Python')], max_length=10),
        ),
    ]
