# Generated by Django 5.1.2 on 2024-12-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_rename_tutorsubjects_taughtsubjects_tutor_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='bio',
            new_name='experience',
        ),
    ]
