# Generated by Django 5.1.2 on 2024-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_lessonrequest_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly'), ('Once', 'Once')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly'), ('Once', 'Once')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
