# Generated by Django 5.1.2 on 2024-12-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_lesson_frequency_alter_lessonrequest_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='from_request',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='lesson_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.lesson'),
        ),
    ]
