# Generated by Django 5.1.2 on 2024-12-06 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_lessonrequest_status_alter_lessonstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('b', 'Booked')], max_length=10),
        ),
    ]
