# Generated by Django 5.1.2 on 2024-12-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_add_notification_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.CharField(choices=[('D', 'day'), ('W', 'week'), ('M', 'month')], default='W', max_length=5),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly')], max_length=10),
        ),
    ]
