# Generated by Django 5.1.2 on 2024-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_tutoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], max_length=10),
        ),
    ]
